{
  ...
}:

{
  # Keep ~/.gitconfig managed so stale pre-Nix includes do not override the XDG
  # Git config generated by Home Manager at ~/.config/git/config. Git may ignore
  # the XDG global config when ~/.gitconfig exists, so include it explicitly.
  home.file.".gitconfig".text = ''
    [include]
        path = ~/.config/git/config
  '';

  programs.git = {
    enable = true;
    # Git itself is installed from nixpkgs-unstable at the system level.
    package = null;

    includes = [
      { path = "~/.config/git/user.gitconfig"; }
      { path = "~/.config/work/gitconfig"; }
    ];

    settings = {
      commit.template = "~/.config/git/committemplate.txt";
      pull.rebase = true;
      push.autoSetupRemote = true;
      difftool.prompt = false;
      merge.conflictstyle = "diff3";
      init.defaultBranch = "main";

      feature.manyFiles = true;

      ghq = {
        vsc = "git";
        root = "~/src";
      };

      url."git@github.com:".insteadOf = "https://github.com/";

      alias = {
        stu = "status --untracked-files=no";
        root = "rev-parse --show-toplevel";
        lg = "log --color --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit --";
        ap = "add --patch";
        psuo = "!git push --set-upstream origin $(git symbolic-ref --short HEAD)";
        "default-branch" = "!git symbolic-ref refs/remotes/origin/HEAD | sed 's@^refs/remotes/origin/@@'";
        cod = "!git checkout $(git default-branch)";
        goreview = "!f() { git diff \${1:-$(git default-branch)} -- . ':(exclude)vendor/'; }; f";
        semtagg = "!f() { tags=$(git semtag -r -ii -fc); if [ -z \"$tags\" ]; then return; else echo \"$tags\" | fzf --ansi; fi; }; f";
        "rebase-squashed" =
          "!f() { case $# in 0) echo 'Usage: git rebase-squashed [target-branch] <original-branch>'; return 1 ;; 1) target=$(git default-branch); original=$1 ;; *) target=$1; original=$2 ;; esac; git rebase --onto \"$target\" $(git merge-base \"$original\" $(git branch --show-current)); }; f";
        pullt = "pull --tags";
        gone = "!f() { default=$(git default-branch); git branch --format='%(refname:short)' | grep -v \"$default\" | xargs -P8 -I{} sh -c 'git diff --quiet \"$1\"...\"$2\" 2>/dev/null && echo \"$2\"' _ \"$default\" {}; }; f";
        "prune-gone" =
          "!f() { git fetch -p && branches=$(git gone | fzf --multi --header='Select branches to delete (TAB to multi-select)'); [ -z \"$branches\" ] && return 0; echo \"$branches\" | xargs git branch -D; }; f";
        randomname = "!echo $(LC_ALL=C tr -dc a-z </dev/urandom | head -c4)";
        save = "!f() { git stash push -m \"\${1:-$(git randomname)}\"; }; f";
        new = "!f() { git fetch origin && git checkout -b \"\${1:-$(git randomname)}\" origin/$(git default-branch); }; f";

        dsf = "diff --color";
        dsfw = "dsf --word-diff";
        dsfs = "dsf --staged";
        dsfsw = "dsf --staged --word-diff";

        dshow = "-c diff.external=difft show --ext-diff";
        dtt = "-c diff.external=difft diff";
        dtts = "-c diff.external=difft diff --staged";
        dtreview = "!f() { git -c diff.external=difft diff \${1:-$(git default-branch)} -- . ':(exclude)vendor/'; }; f";

        prcof = "!GH_FORCE_TTY=yes gh pr list | fzf --ansi --header-lines 3 --preview 'GH_FORCE_TTY=yes gh pr view  {1}' | awk '{ print $1}' | xargs -I {} gh pr checkout {}";
      };

      pager.dsf = "diff-so-fancy | less --tabs=4 -RF";

      diff = {
        hex = {
          textconv = "hexdump -v -C";
          binary = true;
        };
        lockb = {
          textconv = "bun";
          binary = true;
        };
      };
    };
  };

  xdg.configFile."git/committemplate.txt".text = "";
}
